In [ ]:
!pip install -q sentence-transformers datasets torch accelerate

In [ ]:
from datasets import load_dataset
from sentence_transformers import SentenceTransformer, SentenceTransformerTrainer, SentenceTransformerTrainingArguments
from sentence_transformers.losses import MultipleNegativesRankingLoss
from sentence_transformers.training_args import BatchSamplers
import torch

In [ ]:
dataset = load_dataset('Abeshith/research-embedding-dataset')
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['id', 'source_dataset', 'query', 'positive', 'negatives', 'query_id', 'positive_id', 'negative_ids', 'task_type', 'domain'],
        num_rows: 1210
    })
    validation: Dataset({
        features: ['id', 'source_dataset', 'query', 'positive', 'negatives', 'query_id', 'positive_id', 'negative_ids', 'task_type', 'domain'],
        num_rows: 24
    })
})

In [ ]:
dataset['train'][0]

{'id': '86ef4b3968279ffb992c429a14086287',
 'source_dataset': 'mteb/scifact',
 'query': 'Energy balance requires hypothalamic glutamate neurotransmission.',
 'positive': 'Synaptic glutamate release by ventromedial hypothalamic neurons is part of the neurocircuitry that prevents hypoglycemia.. The importance of neuropeptides in the hypothalamus has been experimentally established. Due to difficulties in assessing function in vivo, the roles of the fast-acting neurotransmitters glutamate and GABA are largely unknown. Synaptic vesicular transporters (VGLUTs for glutamate and VGAT for GABA) are required for vesicular uptake and, consequently, synaptic release of neurotransmitters. Ventromedial hypothalamic (VMH) neurons are predominantly glutamatergic and express VGLUT2. To evaluate the role of glutamate release from VMH neurons, we generated mice lacking VGLUT2 selectively in SF1 neurons (a major subset of VMH neurons). These mice have hypoglycemia during fasting secondary to impaired fasting-induced increases in the glucose-raising pancreatic hormone glucagon and impaired induction in liver of mRNAs encoding PGC-1alpha and the gluconeogenic enzymes PEPCK and G6Pase. Similarly, these mice have defective counterregulatory responses to insulin-induced hypoglycemia and 2-deoxyglucose (an antimetabolite). Thus, glutamate release from VMH neurons is an important component of the neurocircuitry that functions to prevent hypoglycemia',
 'negatives': ['The effect of N-acetylcysteine in the nucleus accumbens on neurotransmission and relapse to cocaine.. BACKGROUND Relapse to cocaine seeking has been linked with low glutamate in the nucleus accumbens core (NAcore) causing potentiation of synaptic glutamate transmission from prefrontal cortex (PFC) afferents. Systemic N-acetylcysteine (NAC) has been shown to restore glutamate homeostasis, reduce relapse to cocaine seeking, and depotentiate PFC-NAcore synapses. Here, we examine the effects of NAC applied directly to the NAcore on relapse and neurotransmission in PFC-NAcore synapses, as well as the involvement of the metabotropic glutamate receptors 2/3 (mGluR2/3) and 5 (mGluR5). METHODS Rats were trained to self-administer cocaine for 2 weeks and following extinction received either intra-accumbens NAC or systemic NAC 30 or 120 minutes, respectively, before inducing reinstatement with a conditioned cue or a combined cue and cocaine injection. We also recorded postsynaptic currents using in vitro whole cell recordings in acute slices and measured cystine and glutamate uptake in primary glial cultures. RESULTS NAC microinjection into the NAcore inhibited the reinstatement of cocaine seeking. In slices, a low concentration of NAC reduced the amplitude of evoked glutamatergic synaptic currents in the NAcore in an mGluR2/3-dependent manner, while high doses of NAC increased amplitude in an mGluR5-dependent manner. Both effects depended on NAC uptake through cysteine transporters and activity of the cysteine/glutamate exchanger. Finally, we showed that by blocking mGluR5 the inhibition of cocaine seeking by NAC was potentiated. CONCLUSIONS The effect of NAC on relapse to cocaine seeking depends on the balance between stimulating mGluR2/3 and mGluR5 in the NAcore, and the',
  'Astrocyte-Mediated Distributed Plasticity at Hypothalamic Glutamate Synapses. Afferent activity can induce fast, feed-forward changes in synaptic efficacy that are synapse specific. Using combined electrophysiology, caged molecule photolysis, and Ca(2+) imaging, we describe a plasticity in which the recruitment of astrocytes in response to afferent activity causes a fast and feed-forward, yet distributed increase in the amplitude of quantal synaptic currents at multiple glutamate synapses on magnocellular neurosecretory cells in the hypothalamic paraventricular nucleus. The plasticity is largely multiplicative, consistent with a proportional increase or "scaling" in the strength of all synapses on the neuron. This effect requires a metabotropic glutamate receptor-mediated rise in Ca(2+) in the astrocyte processes surrounding the neuron and the release of the gliotransmitter ATP, which acts on postsynaptic purinergic receptors. These data provide evidence for a form of distributed synaptic plasticity that is feed-forward, expressed quickly, and mediated by the synaptic activation of neighboring astrocytes',
  'Neuronal Sirt1 deficiency increases insulin sensitivity in both brain and peripheral tissues.. Sirt1 is a NAD(+)-dependent class III deacetylase that functions as a cellular energy sensor. In addition to its well-characterized effects in peripheral tissues, emerging evidence suggests that neuronal Sirt1 activity plays a role in the central regulation of energy balance and glucose metabolism. To assess this idea, we generated Sirt1 neuron-specific knockout (SINKO) mice. On both standard chow and HFD, SINKO mice were more insulin sensitive than Sirt1(f/f) mice. Thus, SINKO mice had lower fasting insulin levels, improved glucose tolerance and insulin tolerance, and enhanced systemic insulin sensitivity during hyperinsulinemic euglycemic clamp studies. Hypothalamic insulin sensitivity of SINKO mice was also increased over controls, as assessed by hypothalamic activation of PI3K, phosphorylation of Akt and FoxO1 following systemic insulin injection. Intracerebroventricular injection of insulin led to a greater systemic effect to improve glucose tolerance and insulin sensitivity in SINKO mice compared with controls. In line with the in vivo results, insulin-induced AKT and FoxO1 phosphorylation were potentiated by inhibition of Sirt1 in a cultured hypothalamic cell line. Mechanistically, this effect was traced to a reduced effect of Sirt1 to directly deacetylate and repress IRS-1 function. The enhanced central insulin signaling in SINKO mice was accompanied by increased insulin receptor signal transduction in liver, muscle, and adipose tissue. In summary, we conclude that neuronal Sirt1 negatively regulates hypothalamic insulin signaling, leading to systemic insulin resistance. Interventions that reduce neuronal Sirt1 activity have the potential to improve systemic insulin',
  'In vivo effect of chronic hypoxia on the neurochemical profile of the developing rat hippocampus.. The cognitive deficits observed in children with cyanotic congenital heart disease suggest involvement of the developing hippocampus. Chronic postnatal hypoxia present during infancy in these children may play a role in these impairments. To understand the biochemical mechanisms of hippocampal injury in chronic hypoxia, a neurochemical profile consisting of 15 metabolite concentrations and 2 metabolite ratios in the hippocampus was evaluated in a rat model of chronic postnatal hypoxia using in vivo 1H NMR spectroscopy at 9.4 T. Chronic hypoxia was induced by continuously exposing rats (n = 23) to 10% O2 from postnatal day (P) 3 to P28. Fifteen metabolites were quantified from a volume of 9-11 microl centered on the left hippocampus on P14, P21, and P28 and were compared with normoxic controls (n = 14). The developmental trajectory of neurochemicals in chronic hypoxia was similar to that seen in normoxia. However, chronic hypoxia had an effect on the concentrations of the following neurochemicals: aspartate, creatine, phosphocreatine, GABA, glutamate, glutamine, glutathione, myoinositol, N-acetylaspartate (NAA), phosphorylethanolamine, and phosphocreatine/creatine (PCr/Cr) and glutamate/glutamine (Glu/Gln) ratios (P < 0.001 each, except glutamate, P = 0.04). The increased PCr/Cr ratio is consistent with decreased brain energy consumption. Given the well-established link between excitatory neurotransmission and brain energy metabolism, we postulate that elevated glutamate, Glu/Gln ratio, and GABA indicate suppressed excitatory neurotransmission in an energy-limited environment. Decreased NAA and phosphorylethanolamine suggest reduced neuronal integrity and phospholipid'],
 'query_id': '378',
 'positive_id': '11886686',
 'negative_ids': ['4700428', '16398827', '2481032', '14782049'],
 'task_type': 'scientific_claim_retrieval',
 'domain': 'scientific'}

In [ ]:
train_dataset = dataset['train'].shuffle(seed=42).map(lambda x: {
    'query': x['query'],
    'positive': x['positive'],
})

Map:   0%|          | 0/1210 [00:00<?, ? examples/s]

In [ ]:
eval_dataset = dataset['validation']

In [ ]:
model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
loss = MultipleNegativesRankingLoss(model)

In [ ]:
args = SentenceTransformerTrainingArguments(
    output_dir='./finetuned-research-embedding',
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    warmup_ratio=0.1,
    fp16=True,
    batch_sampler=BatchSamplers.NO_DUPLICATES,
    logging_steps=10,
    save_strategy='epoch',
    eval_strategy='epoch',
    save_total_limit=2,
    load_best_model_at_end=True,
)

WARNING:sentence_transformers.training_args:The `warmup_ratio` argument is deprecated in Transformers v5+, and will also be removed from Sentence Transformers once support for Transformers v4 is dropped. Since you're using Transformers v5+, please use `warmup_steps` (as a float) to specify the warmup ratio instead.

In [ ]:
trainer = SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    loss=loss,
)

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

In [ ]:
trainer.train()

WARNING:sentence_transformers.data_collator:Column 'positive' is at index 3, whereas a column with this name is usually expected at index 1. Note that the column order can be important for some losses, e.g. MultipleNegativesRankingLoss will always consider the first column as the anchor and the second as the positive, regardless of the dataset column names. Consider renaming the columns to match the expected order, e.g.:
dataset = dataset.select_columns(['anchor', 'positive', 'negative'])

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

TrainOutput(global_step=456, training_loss=0.15750344176041453, metrics={'train_runtime': 416.8006, 'train_samples_per_second': 8.709, 'train_steps_per_second': 1.094, 'total_flos': 0.0, 'train_loss': 0.15750344176041453, 'epoch': 3.0})

In [ ]:
args.num_train_epochs = 10
trainer.train(resume_from_checkpoint=True)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

TrainOutput(global_step=1520, training_loss=1.1626042817768299e-06, metrics={'train_runtime': 977.4935, 'train_samples_per_second': 12.379, 'train_steps_per_second': 1.555, 'total_flos': 0.0, 'train_loss': 1.1626042817768299e-06, 'epoch': 10.0})

In [ ]:
trainer.save_model('./finetuned-research-embedding-final')

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
base_model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
finetuned_model = SentenceTransformer('./finetuned-research-embedding-final')

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [ ]:
from sentence_transformers import SentenceTransformer, util

base_similarities = []
finetuned_similarities = []

for i in range(min(10, len(eval_dataset))):  # First 10 samples
    sample = eval_dataset[i]
    query_emb_base = base_model.encode(sample['query'], convert_to_tensor=True)
    pos_emb_base = base_model.encode(sample['positive'], convert_to_tensor=True)
    base_sim = util.cos_sim(query_emb_base, pos_emb_base)[0][0].item()

    query_emb_ft = finetuned_model.encode(sample['query'], convert_to_tensor=True)
    pos_emb_ft = finetuned_model.encode(sample['positive'], convert_to_tensor=True)
    ft_sim = util.cos_sim(query_emb_ft, pos_emb_ft)[0][0].item()

    base_similarities.append(base_sim)
    finetuned_similarities.append(ft_sim)

    print(f"Sample {i+1:2d}: Base={base_sim:.4f} | Finetuned={ft_sim:.4f} | Δ={ft_sim-base_sim:+.4f}")

Sample  1: Base=0.8143 | Finetuned=0.8242 | Δ=+0.0099
Sample  2: Base=0.3958 | Finetuned=0.3839 | Δ=-0.0119
Sample  3: Base=0.3679 | Finetuned=0.3626 | Δ=-0.0053
Sample  4: Base=0.3909 | Finetuned=0.4090 | Δ=+0.0180
Sample  5: Base=0.5675 | Finetuned=0.5481 | Δ=-0.0195
Sample  6: Base=0.3717 | Finetuned=0.4104 | Δ=+0.0387
Sample  7: Base=0.5119 | Finetuned=0.5274 | Δ=+0.0154
Sample  8: Base=0.8704 | Finetuned=0.8653 | Δ=-0.0051
Sample  9: Base=0.5099 | Finetuned=0.5273 | Δ=+0.0175
Sample 10: Base=0.5155 | Finetuned=0.5377 | Δ=+0.0222

In [ ]:
import numpy as np

print(f"\nAvg Cosine Sim - Base: {np.mean(base_similarities):.4f} | Finetuned: {np.mean(finetuned_similarities):.4f}")
print(f"Improvement: {np.mean(finetuned_similarities) - np.mean(base_similarities):+.4f}")

Avg Cosine Sim - Base: 0.5316 | Finetuned: 0.5396
Improvement: +0.0080

In [ ]:
train_queries = dataset['train']['query'][100:110]
train_docs = dataset['train']['positive'][100:150]

base_scores_all = []
ft_scores_all = []

# Test each query against full doc corpus
for i, query in enumerate(train_queries):
    print(f"Query {i+1}: {query[:80]}...")

    # Encode query + all docs
    q_base = base_model.encode([query])
    q_ft = finetuned_model.encode([query])
    docs_base = base_model.encode(train_docs, show_progress_bar=False)
    docs_ft = finetuned_model.encode(train_docs, show_progress_bar=False)

    # Cosine similarity scores
    base_scores = util.cos_sim(q_base, docs_base)[0]
    ft_scores = util.cos_sim(q_ft, docs_ft)[0]

    # Store top scores
    base_scores_all.extend(base_scores.cpu().numpy())
    ft_scores_all.extend(ft_scores.cpu().numpy())

    # Show top-3 for this query
    base_top3 = base_scores.topk(3).values.cpu().numpy()
    ft_top3 = ft_scores.topk(3).values.cpu().numpy()

    print(f"  Base Top-3:  [{base_top3[0]:.4f}, {base_top3[1]:.4f}, {base_top3[2]:.4f}]")
    print(f"  Finetuned Top-3: [{ft_top3[0]:.4f}, {ft_top3[1]:.4f}, {ft_top3[2]:.4f}]")
    print()

Query 1: what are best practices in hospitals and at home in maintaining quarantine?...
  Base Top-3:  [0.4116, 0.4040, 0.3975]
  Finetuned Top-3: [0.4033, 0.3949, 0.3935]

Query 2: what are the best masks for preventing infection by Covid-19?...
  Base Top-3:  [0.5270, 0.3327, 0.3300]
  Finetuned Top-3: [0.5380, 0.3171, 0.3111]

Query 3: Satellite cell dysfunction is a key factor in sarcopenia development....
  Base Top-3:  [0.6642, 0.4285, 0.4133]
  Finetuned Top-3: [0.6710, 0.4644, 0.4494]

Query 4: Ambulatory blood pressure monitoring is inaccurate at diagnosing hypertension....
  Base Top-3:  [0.6592, 0.3892, 0.2564]
  Finetuned Top-3: [0.6717, 0.3763, 0.2459]

Query 5: What is the mechanism of inflammatory response and pathogenesis of COVID-19 case...
  Base Top-3:  [0.5676, 0.4675, 0.4675]
  Finetuned Top-3: [0.5850, 0.4881, 0.4881]

Query 6: How does the coronavirus differ from seasonal flu?...
  Base Top-3:  [0.4442, 0.3833, 0.3806]
  Finetuned Top-3: [0.4222, 0.3622, 0.3418]

Query 7: Environmentally-induced senescence is mimicked in disease modeling by adding spe...
  Base Top-3:  [0.5422, 0.4821, 0.4137]
  Finetuned Top-3: [0.5492, 0.5132, 0.4464]

Query 8: are there serological tests that detect antibodies to coronavirus?...
  Base Top-3:  [0.4567, 0.4053, 0.2874]
  Finetuned Top-3: [0.4371, 0.3958, 0.2735]

Query 9: are cardiac complications likely in patients with COVID-19?...
  Base Top-3:  [0.4665, 0.4307, 0.3976]
  Finetuned Top-3: [0.4562, 0.4102, 0.4040]

Query 10: Ribosome-inactivating protein-2 (RIP-2) interacts with the p75 NTR death domain...
  Base Top-3:  [0.4170, 0.4096, 0.3770]
  Finetuned Top-3: [0.4071, 0.4050, 0.3624]

In [ ]:
!pip install huggingface_hub

In [ ]:
from huggingface_hub import notebook_login
notebook_login()

In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('./finetuned-research-embedding-final')
model.push_to_hub("Abeshith/research-embedding-finetuned")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...ylbuxxe/model.safetensors:   2%|2         | 10.7MB /  438MB

'https://huggingface.co/Abeshith/research-embedding-finetuned/commit/1e673b828aad977e99e4a5eedb0c268bfb922b13'